### ISSUE TITLE
There is a problem with your VIPPs

### ISSUE THREAD

**Issue by emilshamloo** [vippsas/vipps-magento#32]
Magento ver 2.3.0
It's been over 2 week I have this issu, I contacted Vipps support and they told me to contact here.
The support checked the API-keys, and they worked as they should.
I've got the new ones now. 
Here it is a film:
http://recordit.co/fnMDFHQPFp

**Comment by aluminium1989** [comment]
Hi @emilshamloo 
Thank you for request.
Could you share __MAGENTOROOT__/var/log/vipps_exception.log content when the error appears?
Do you have multi-website setup on this instance?

**Comment by emilshamloo** [comment]
-I'll upload the vipps_exception.log here.
https://drive.google.com/file/d/1E6hkgRTQlbiJpuOUFCI2hi1Z-6u9GQZ4/view?usp=sharing
-No, I do not have multi-website setup!
-https://www.delikatematgaver.no/
Thanks

**Comment by aluminium1989** [comment]
@emilshamloo thank you for providing exception log.
We are working on the issue.

**Comment by aluminium1989** [comment]
Please try to truncate the table vipps_payment_jwt and let me know if it helped.

**Comment by aluminium1989** [comment]
Hi @emilshamloo 
I'm adding the patch [here](https://github.com/vippsas/vipps-magento/files/3062905/Zend_Http_Response.patch.zip) for Zend Response to debug headers that come from the server on token request.
1. Can you please apply the patch.
- Put and unpack it to the root dir of the project.
- execute `patch -p0 < Zend_Http_Response.patch`
2. And reproduce the issue.
You will get the new log file vipps_extra.log that contains information from Vipps response.
3. Remove patch `patch -p0 -R < Zend_Http_Response.patch`

Please send vipps_extra.log it to vipps@vaimo.com

**Comment by aluminium1989** [comment]
Closing this issue, as there has been no activity for two weeks

**Comment by emilshamloo** [comment]
Hi, I've got contacted by a great guy named Oleg whom told me that my extension could be old. When I tried to upgrade, we found that it was installed manually. I found a developer whom cleaned my installation from the old manually installed extension. 
Now the newest version of Vipps is installed on my site via composer.
But I have still the same problem.
http://recordit.co/fnMDFHQPFp

**Comment by cloveras** [comment]
Re-opening.

**Comment by aluminium1989** [comment]
Hi @emilshamloo.
Please follow these steps to reinstall module tables.
0. Make sure that Vipps module is enabled: `$PROJECT_DIR$/bin/magento module:status`.
1. Run mysql command in project database: `DELETE FROM setup_module WHERE module LIKE 'Vipps_Payment';`
2. Than run this command in linux terminal `$PROJECT_DIR$/bin/magento setup:upgrade`

Please let me know the result.

**Comment by emilshamloo** [comment]
Hello, 
My developer asked me to post this error to see if we can solve the issue!
Vipps\Payment\Gateway\Exception\AuthenticationException: The request does not match any route. in /home/delikzrx/public_html/vendor/vipps/module-payment/Model/TokenProvider.php:193

**Comment by emilshamloo** [comment]
I attach the log file as well!
[2019-05-14 12:26:26] vipps.CRITICAL: Invalid header line detected [] []
[2019-05-14 12:26:26] vipps.CRITICAL: Vipps\Payment\Gateway\Exception\AuthenticationException: Kan ikke hente access token fra Vipps. in /home/delikzrx/public_html/vendor/vipps/module-payment/Model/TokenProvider.php:193
Stack trace:
#0 /home/delikzrx/public_html/vendor/vipps/module-payment/Model/TokenProvider.php(153): Vipps\Payment\Model\TokenProvider->readJwt()
#1 /home/delikzrx/public_html/vendor/vipps/module-payment/Model/TokenProvider.php(125): Vipps\Payment\Model\TokenProvider->regenerate()
#2 /home/delikzrx/public_html/vendor/vipps/module-payment/Gateway/Http/Client/Curl.php(156): Vipps\Payment\Model\TokenProvider->get()
#3 /home/delikzrx/public_html/vendor/vipps/module-payment/Gateway/Http/Client/Curl.php(133): Vipps\Payment\Gateway\Http\Client\Curl->getHeaders(Array)
#4 /home/delikzrx/public_html/vendor/vipps/module-payment/Gateway/Http/Client/Curl.php(92): Vipps\Payment\Gateway\Http\Client\Curl->place(Object(Magento\Payment\Gateway\Http\Transfer))
#5 /home/delikzrx/public_html/vendor/vipps/module-payment/Gateway/Command/GatewayCommand.php(139): Vipps\Payment\Gateway\Http\Client\Curl->placeRequest(Object(Magento\Payment\Gateway\Http\Transfer))
#6 /home/delikzrx/public_html/vendor/magento/module-payment/Gateway/Command/CommandManager.php(65): Vipps\Payment\Gateway\Command\GatewayCommand->execute(Array)
#7 /home/delikzrx/public_html/vendor/vipps/module-payment/Gateway/Command/CommandManager.php(132): Magento\Payment\Gateway\Command\CommandManager->executeByCode('initiate', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Array)
#8 /home/delikzrx/public_html/vendor/vipps/module-payment/Gateway/Command/CommandManager.php(59): Vipps\Payment\Gateway\Command\CommandManager->executeByCode('initiate', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Array)
#9 /home/delikzrx/public_html/vendor/vipps/module-payment/Controller/Payment/Regular.php(86): Vipps\Payment\Gateway\Command\CommandManager->initiatePayment(Object(Magento\Quote\Model\Quote\Payment\Interceptor), Array)
#10 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Vipps\Payment\Controller\Payment\Regular->execute()
#11 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Vipps\Payment\Controller\Payment\Regular\Interceptor->___callParent('execute', Array)
#12 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Vipps\Payment\Controller\Payment\Regular\Interceptor->Magento\Framework\Interception\{closure}()
#13 /home/delikzrx/public_html/generated/code/Vipps/Payment/Controller/Payment/Regular/Interceptor.php(26): Vipps\Payment\Controller\Payment\Regular\Interceptor->___callPlugins('execute', Array, Array)
#14 /home/delikzrx/public_html/vendor/magento/framework/App/Action/Action.php(108): Vipps\Payment\Controller\Payment\Regular\Interceptor->execute()
#15 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Vipps\Payment\Controller\Payment\Regular\Interceptor->___callParent('dispatch', Array)
#17 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Vipps\Payment\Controller\Payment\Regular\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /home/delikzrx/public_html/generated/code/Vipps/Payment/Controller/Payment/Regular/Interceptor.php(39): Vipps\Payment\Controller\Payment\Regular\Interceptor->___callPlugins('dispatch', Array, Array)
#19 /home/delikzrx/public_html/vendor/magento/framework/App/FrontController.php(159): Vipps\Payment\Controller\Payment\Regular\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /home/delikzrx/public_html/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Vipps\Payment\Controller\Payment\Regular\Interceptor))
#21 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /home/delikzrx/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /home/delikzrx/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /home/delikzrx/public_html/vendor/swissup/module-amp/Plugin/Framework/FrontController.php(48): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Swissup\Amp\Plugin\Framework\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/delikzrx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /home/delikzrx/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#31 /home/delikzrx/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /home/delikzrx/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#33 /home/delikzrx/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#34 /home/delikzrx/public_html/index.php(38): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#35 {main} [] []
[2019-05-14 12:26:26] vipps.CRITICAL: Kan ikke hente access token fra Vipps. [] []

**Comment by cloveras** [comment]
Hi, @emilshamloo 

Have you completed the steps as described by @aluminium1989 above?

What did you do before you got the error?

Christian, Vipps

**Comment by cloveras** [comment]
Hi, @emilshamloo 

The `vipps.CRITICAL: Kan ikke hente access token fra Vipps` error is from the `POST:/accessToken/get` API call, and indicates invalid credentials.

Can you please verify that you have the correct credentials by using our Postman collection with your credentials: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-postman.md

Christian, Vipps

**Comment by emilshamloo** [comment]
My developer is going to check the postman.md
but in the meanwhile, how can I be sure that I've used correct credentials? Is there any manual to help me add credential one more time?

**Comment by emilshamloo** [comment]
It's been 2 days ago, I have asked a question. Anyboady can help me?

**Comment by cloveras** [comment]
Hi, @emilshamloo 

The best way to check the credentials is with Postman. See the Postman guide in the link above.

As explained in a previous email, the credentials are added to Magento as described in the install file: https://github.com/vippsas/vipps-magento/blob/master/INSTALL.md

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Hi

I am a developer to work on Emil's magento site. So we are configuring Vipps payment method.
But we have the sql error in upgrading the modules after we installed the extension.

$ php bin/magento setup:upgrade
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'delikzrx_backup.mga3_vipps_quote' doesn't exist, query was: SHOW CREATE TABLE mga3_vipps_quote

I noticed the Vipps extension created 4 tables - mga3_vipps_payment_jwt, mga3_vipps_profiling, vipps_quote, vipps_quote_attempt. 
If I drop these 4 tables from database, the module upgrading is done successfully without any error.
We are using "mga3_" as table prefix. Why two tables are created with the table prefix but the rest of two tables are created without the prefix?

I think Vipps payment is not working on our site properly because of this issue.

Kind Regards.
Noeli

**Comment by emilshamloo** [comment]
Hi, and thanks to @noeli-eshopguru my developer to help me out in this issue.
From my side, as a merchant, I would like to add keys once more to be sure, that I've done my job correct.
Am I correct when I copy/paste the Primary key- Default accessstoken
and Secondary key Ecommerce-Delikatematgaver ? To Subscription1 and Subscription2?
 please, look at the attache picture
![image](https://user-images.githubusercontent.com/2904897/57910200-fdc3e200-7884-11e9-85f3-4aca259b240c.png)

**Comment by noeli-eshopguru** [comment]
Hi

Can you give me an answer ASAP?

Kind Regards.
Noeli

**Comment by noeli-eshopguru** [comment]
Hi, how are you?

I tested the credentials for Vipps on the Postman.
So we are getting this error in sending Access Token request.
![image](https://user-images.githubusercontent.com/50664110/58072101-3fc88d00-7bd1-11e9-8a08-cb7210bdcb5c.png)

Kind Regards.
Noeli

**Comment by SmolyarO** [comment]
Hi @emilshamloo and @noeli-eshopguru
Not really correct. Both have to be Primary Keys. 
Subscription Key 1 -> DEFAULT_A... Primary key
Subscription Key 2 -> ECOMMERCE-... Primary key

**Comment by noeli-eshopguru** [comment]
Hi

I already set Ocp-Apim-Subscription-Key-Access-Token and Ocp-Apim-Subscription-Key-Ecom as DEFAULT_A... Primary key and ECOMMERCE-... Primary key correctly on Postman.
But we are getting the error above.

Kind Regards.
Noeli

**Comment by cloveras** [comment]
Hi, @noeli-eshopguru and @emilshamloo 

Can you please confirm that you are using primary keys for both values, as @SmolyarO wrote above? The arrows in the screenshot indicates that the `Secondary key` is used for `Subscription Key 2`. This is documented here: https://github.com/vippsas/vipps-magento/blob/master/INSTALL.md#basic-vipps-settings

Are you sure the SQL/db issues are fixed? It seems like you have not originally installed the module as described in the documentation? A "clean" install may be required: https://github.com/vippsas/vipps-magento/blob/master/INSTALL.md#installation-via-composer-recommended

I have (again) checked sale unit 540443 for orgno. 993879770, and everything looks good in our systems.

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Hi @cloveras 

I tested with the primary keys on Postman exactly. But I am getting the error above.
![image](https://user-images.githubusercontent.com/50664110/58212446-6b5a8d00-7d21-11e9-8c02-751f59fa74ef.png)

And I installed the Vipps extension just like this guide: https://github.com/vippsas/vipps-magento/blob/master/INSTALL.md#installation-via-composer-recommended.
But two tables have the table prefix and another two ones haven't the prefix.
Then if I upgrade the magento modules on the command prompt, I get the SQL error with Vipps extension.

$ php bin/magento setup:upgrade
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'delikzrx_backup.mga3_vipps_quote' doesn't exist, query was: SHOW CREATE TABLE mga3_vipps_quote

Why are they happening?

Kind Regards.
Noeli

**Comment by simenarvnes** [comment]
What is the value of the {{base_url}} variable?

**Comment by aluminium1989** [comment]
Hi @noeli-eshopguru.
Can you please show the list of existent tables with '%vipps_quote%' prefix in your database?
`show tables like '%vipps_quote%'`
And let me know installed version of the module.
`select * from setup_module where module = 'Vipps_Payment';`

**Comment by aluminium1989** [comment]
@noeli-eshopguru 
You should have these 4 tables started from _vipps_ prefix in your database.
`vipps_payment_jwt`, `vipps_profiling`, `vipps_quote`, `vipps_quote_attempt`.
If not, please reinstall the module.

**Comment by aluminium1989** [comment]
@emilshamloo 

Please share SSH access to your website on integration@vipps.no
We can help you to install the module.

**Comment by noeli-eshopguru** [comment]
Hi @simenarvnes 

You mean base_url on Postman?
![image](https://user-images.githubusercontent.com/50664110/58260100-73a9db00-7da8-11e9-89b4-941ba60961d1.png)

Kind Regards.
Noeli

**Comment by noeli-eshopguru** [comment]
Hi @aluminium1989 

Do you want SSH for our website?

Kind Regards.
Noeli

**Comment by cloveras** [comment]
Hi

It seems we return a HTTP/2 response from `POST:/accesstoken/get`, and that Magento does not handle this.

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Hi @cloveras 

I hope you will solve the problem ASAP.
And how about the table creation issue?
I have already posted this issue above.

$ php bin/magento setup:upgrade
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'delikzrx_backup.mga3_vipps_quote' doesn't exist, query was: SHOW CREATE TABLE mga3_vipps_quote

Kind Regards.
Noeli

**Comment by aluminium1989** [comment]
@noeli-eshopguru,
The issue with lost tables has been fixed. Please update the module to avoid it in future.
Do you have the access to the hosting panel? Can you switch it http1.1 protocol?

**Comment by cloveras** [comment]
Hi

It seems I misunderstood: Vipps does _not_ send `HTTP/2` unless the client negotiates it. We default to `HTTP/1.1`.

Also: It seems we return `HTTP/1.1`, but that it is changed to `HTTP/2` on your end.

@aluminium1989 is looking into this on your server with the SSH details you provided.

Christian, Vipps

**Comment by cloveras** [comment]
Hi again, @noeli-eshopguru and @emilshamloo 

It seems you are using cpanel, so here is the documentation for disabling `HTTP/2`:
https://documentation.cpanel.net/display/EA4/Apache+Module%3A+HTTP2#ApacheModule:HTTP2-Howtoinstalloruninstallmod_http2

Now that the database has been fixed fore you, and we have found the `HTTP/2` problem, I hope you can make the last changes to get Vipps working on your website.

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Hi

I reinstalled Vipps module and 4 tables with our table prefix were created exactly.
But we are getting another error when we upgrade the modules.
![image](https://user-images.githubusercontent.com/50664110/58327805-1e7ecf80-7e63-11e9-956c-91258490f491.png)

Can you take a look for it?

Kind Regards.
Noeli

**Comment by cloveras** [comment]
Hi

Please check the db scripts to check which tables are created during installation, and which are not. 

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Hi

During installation, total 4 tables are created.
mga3_vipps_payment_jwt, mga3_vipps_profiling, mga3_vipps_quote, mga3_vipps_quote_attempt

Kind Regards.
Noeli

**Comment by aluminium1989** [comment]
@noeli-eshopguru 
Tables set is installed correctly. Do you have still any issue?

**Comment by emilshamloo** [comment]
I've asked my server support to disable the HTTP2, but they say that it can't be done! It is necessary to have https!

**Comment by noeli-eshopguru** [comment]
Hi @aluminium1989 

didn't you see the error message above?

I reinstalled Vipps module and 4 tables with our table prefix were created exactly.
But we are getting another error when we upgrade the modules.
![image](https://user-images.githubusercontent.com/50664110/58327805-1e7ecf80-7e63-11e9-956c-91258490f491.png)

If I drop 4 vipps tables from database, the module upgrade is done without any error.
Can you take a look for it?

Kind Regards.
Noeli

**Comment by cloveras** [comment]
Hi, @noeli-eshopguru 

As @aluminium1989 wrote above: "Tables set is installed correctly. Do you have still any issue?"

The error above seems like _exactly_ the same error Oleg helped with earlier. Have you, after Oleg corrected your database tables, made changes to it? If so, please revert them. 

We want to help, but we strongly recommend using the standard installation methods, and gthat our documentation is followed. If you do things differently, you also have to be able to get things working "your way".

We can not continue to (repeatedly) correct database issues caused by a custom installation. We offer the module as open source, and we investin in improving it for everyone, but we can not offer unlimited, free support for custom installations.

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Hi @cloveras and @aluminium1989

I have never changed anything in codebase and dababase recently.
But I am still getting the same error above.
I installed Vipps extension with your guide exactly.
I am a magento specialist and very familiar with composer installation.
I am not sure what @aluminium1989 modified on our database.
After I reinstalled your modified extension, the table prefix error was fixed and created 4 tables with our prefix correctly.
I think your extension has some issues with upgrading the modules for magento 2.
I hope you will fix those issue ASAP.

Kind Regards.
Noeli

**Comment by cloveras** [comment]
Hi, @noeli-eshopguru 

@aluminium1989 is investigating the index error, and will post an update here ASAP.

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Thanks you!

**Comment by aluminium1989** [comment]
Hi @noeli-eshopguru,

Please reinstall the module from repository (ignore composer cache).
The issue "undefined quote" should be fixed.

**Comment by cloveras** [comment]
Hi, @noeli-eshopguru 

For details about the changes you will get when updating the module, see: https://github.com/vippsas/vipps-magento/releases

Wer have also updated the prerequisites with HTTP/1.1 and HTTP/2 details: https://github.com/vippsas/vipps-magento#pre-requisites

I hope the steps above solves the issues, and that you are able to get Vipps for Magento to work on your site.

If you have other issues or questions, please create seperate issues for each one.

Christian, Vipps

**Comment by noeli-eshopguru** [comment]
Hi

I updated the extension on our site. So the module upgrade issue was fixed.
But we are still getting the same error like before on the checkout page.

I am not sure why it's getting 401 error on Postman test.
https://user-images.githubusercontent.com/50664110/58072101-3fc88d00-7bd1-11e9-8a08-cb7210bdcb5c.png

Kind Regards.
Noeli

**Comment by emilshamloo** [comment]
Hello, @SmolyarO 
@noeli-eshopguru  reports me that the extension is reinstalled now without any error.
I have copy and pasted the following keys.
Please, let me know if it was correct?
![keys](https://user-images.githubusercontent.com/2904897/58618021-d5df7000-82c1-11e9-86f3-ee94e1eb865f.jpg)
If it was correct, then why I still get error in the checkout page?
Regards

**Comment by voleye** [comment]
Hi @emilshamloo, to solve the issue I would like to propose to validate your credentials first.
Could you please confirm that you can successfully get access token using postman?

**Comment by voleye** [comment]
@emilshamloo Regarding your previous comment - DEFAULT_ACCESSTOKEN should be putted into both: Subscription key 1 and  Subscription key 2

**Comment by noeli-eshopguru** [comment]
Hi

I posted already two times about my postman testing result. But we didn't get the correct answer from you. I will post it here again.

> Hi, how are you?
> 
> I tested the credentials for Vipps on the Postman.
> So we are getting this error in sending Access Token request.
> ![image](https://user-images.githubusercontent.com/50664110/58072101-3fc88d00-7bd1-11e9-8a08-cb7210bdcb5c.png)
> 
> Kind Regards.
> Noeli

Thanks

**Comment by voleye** [comment]
Hi @noeli-eshopguru sorry about that. This thread is enough big and many persons take a part in it, so I decided to clarify one more time to be sure what the correct status for now.

My main concern is to clarify what we are trying to solve. Is this an issue with module or the issue with Vipps credentials. When we are trying to connect to Vipps and get an access token using postman than Magento plugin/module/extension does not take a part in this process and now our focus should be on getting correct credentials and make it works using just postman. 

In this case we will know for sure that credentials is fine.

Let me clarify one more thing, is everything fine with pair url -> credentials? I mean are you using test url or live url? I just assume that using test url but credentials for live env. it can leads to such issues.

My apologize if you already wrote about it.

**Comment by emilshamloo** [comment]
I try to recheck credentials, but I get this error!
![image](https://user-images.githubusercontent.com/2904897/59268688-8ef06380-8c4d-11e9-842c-74144ecf58c9.png)

**Comment by noeli-eshopguru** [comment]
Hi @voleye 

Do you mean the url using on postman?
I think there is nothing any variable for magento site url in postman.
I have only tested with Vipps credentials.

Kind Regards.
Noeli

**Comment by cloveras** [comment]
Hi, @noeli-eshopguru 

To make sure the Vipps credentials are correct, and without doing anything in/with Magento, can you please check the credentials (using the correct test or production URL) in Postman, as described here? https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-postman.md

And, of course: Plese do not post any credentials publicly.

@emilshamloo: Are you following the instructions here? https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md Which username are you loggin in with, and in which environment?

Christian, Vipps

**Comment by emilshamloo** [comment]
Thanks @cloveras 
Yes, I am following steps in the instructions you've mentioned!
NB! I've loged inn before and it is a known logging process for me.
I use this environment and username:
I use to use Incognito!
https://apitest-portal.vipps.no/
supermarket.nodagligvarerpnettemilshamloo@apivipps.no

**Comment by cloveras** [comment]
Hi, @emilshamloo 

We are working on making the API keys available on portal.vipps.no, and it looks like we might get it in place today (or tomorrow). Hopefully that will help.

Christian, Vipps

**Comment by emilshamloo** [comment]
Hi, @cloveras , Is there any news?

**Comment by emilshamloo** [comment]
Hi, @cloveras , I am still waiting!

**Comment by chizhov13** [comment]
@emilshamloo @voleye  @aluminium1989 hi there, I have the same issue. I got Bearer token via Postman without any problems. But it doesn't work on the checkout. Every time I get an error related to token.

Rows from vipps_debug.log
```
[2019-06-27 14:39:25] vipps.CRITICAL: Invalid header line detected [] []
[2019-06-27 14:39:25] vipps.CRITICAL: Vipps\Payment\Gateway\Exception\AuthenticationException: Kan ikke hente access token fra Vipps. in /home/web/public/vendor/vipps/module-payment/Model/TokenProvider.php:193
/** Stack trace **/
[2019-06-27 14:39:25] vipps.CRITICAL: Kan ikke hente access token fra Vipps. [] []
```
Please, fix it asap.

**Comment by emilshamloo** [comment]
Hi, I have still the same problem. 
I did not have time untill now, and I can try to solve this issue now.
Who can help me solve this issue?
Regards
Emil

**Comment by emilshamloo** [comment]
I think it is much better for me to open a new case!

**Comment by cloveras** [comment]
Hi, @emilshamloo 

As mentioned on email, this is the best place to get help. The developers of the plugin can help directly, and it's also possible to help others at the same time, like @chizhov13, who has similar problems.

I'm sorry about the slow response here, we will fix that.

Christian, Vipps

**Comment by cloveras** [comment]
Hi again, @emilshamloo and @chizhov13 

I have talked with Vaimo (https://www.vaimo.com), who develops and maintains this plugin for Vipps, and they will look into this right away. I'm very sorry for the lack of response here, we will make sure to follow up much better.

Please note that API keys are now retrieved from portal.vipps.no, where you log in with BankID: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md#getting-the-api-keys

Please make sure that you use the correct API keys, and that the test and production environments are completely separate. The API keys for api.vipps.no do not work for apitest.vipps.no, and vice versa.

Christian, Vipps

**Comment by matsjohans** [comment]
Hi,

Additional to Christians comment above, also make sure to set the Magento module in the correct mode. 
_Stores > Configuration > Sales > Payment methods > Vipps_
Test environment: Develop
Production environment: Production

Regards
Mats, Vipps

**Comment by emilshamloo** [comment]
Hi,
Today I have checked these points to be sure if they are correct:
- The enviornment is corresponding to the mode of my installation. It means both are in the "developer" mode.
http://prntscr.com/qv3df5
http://prntscr.com/qv3dpa
- I re-entered all of credentials from https://portal.vipps.no/
http://prntscr.com/qv3hux

**Comment by matsjohans** [comment]
Hi, 

I see from your last screenshot you are using production keys. You need to set module settings to _Production_ for these keys. You may use these and add some low price products to your site to test in production. And then refund or cancel afterwards. 

Regards
Mats, Vipps

**Comment by emilshamloo** [comment]
Thanks Mats.
Now I changed the Environment of my Magento to Production:
http://prntscr.com/qv4dtm
But did not helped either.

**Comment by emilshamloo** [comment]
Now I am going to change the Module setting to production to see if it will help.
No, It did not helped. And I am testing in the Incognito, then I do not have any cache.
My Magento enviroment is in Production mode and my Module setting is in Production mode!
http://prntscr.com/qv4gne

**Comment by cloveras** [comment]
Hi

Ok, so just to be sure: 

1. You are now using the API keys for production, fetched from portal.vipps.no.
2. You are running Magento in Production mode.

Correct? Please double check this, as the screenshots yesterday showed that you attempted to use the API keys fro production in Developer (test) mode.

Can you give some more details of what goes wrong? 
Do you get any errors?

Christian, Vipps

**Comment by voleye** [comment]
Hi @emilshamloo let me clarify what the issue is? Sorry about that is because of long period of time, but I still would like to split the issue into two parts - does the issue with credentials or with a module?
As I wrote before 

> My main concern is to clarify what we are trying to solve. Is this an issue with module or the issue with Vipps credentials. When we are trying to connect to Vipps and get an access token using postman than Magento plugin/module/extension does not take a part in this process and now our focus should be on getting correct credentials and make it works using just postman.

> In this case we will know for sure that credentials is fine.

**Comment by emilshamloo** [comment]
Hello, @voleye 
I am not sure which part has problem, the credentials or module!

I am not an expert and I am not familiar with your terms of professional language :-(

As a merchant, I add provided credentials to my web interface, and that's it.

https://prnt.sc/qview5

http://prntscr.com/qvldmo

Thanks for your support

**Comment by voleye** [comment]
@emilshamloo fine, now, let me clarify what the issue is? Do you see any error?
Could you provide expected and actual result?

**Comment by cloveras** [comment]
(This issue is now handled directly between @emilshamloo and @voleye, by @emilshamloo creating a new admin user that @voleye can use)

**Comment by voleye** [comment]
Issue solved, there is an issue with Magento version that does not support HTTPS/2, solved using patch. We will update our documentation soon by adding more information what Magento versions have the issue and how to handle it. I will close this PR

**Comment by cloveras** [comment]
Hi

Ok, HTTP/2 is already documented the README, but it seems it needs to be clearer: https://github.com/vippsas/vipps-magento/blob/master/README.md#prerequisites

Christian, Vipps

**Comment by emilshamloo** [comment]
Hi, @cloveras and @voleye 
I have to re-open this ticket.
Volodymyr has solved my issue, but in my checkout page there are three additional question, my customer has to answer. Vipps can not transfer these information to Magetnto2.
Volodymyr told me that he is going to solve this issue, but I think he has forgotten me :-(
I have contacted him, but I do not get any answer!
Can you help me?

**Comment by cloveras** [comment]
(I reopened the issue)

**Comment by cloveras** [comment]
☝️ @voleye

**Comment by emilshamloo** [comment]
Any news for me?

**Comment by voleye** [comment]
Hi @emilshamloo, happy to inform you that it has been fixed in new release, https://github.com/vippsas/vipps-magento/releases/tag/2.3.0

**Comment by emilshamloo** [comment]
Hello, what dose this mean for me? Should I upgrade? Update? If so, can you please do it for me? You have access to the backend. RegarMvhEmil Shamloo -------- Opprinnelig melding --------Fra: Volodymyr Klymenko <notifications@github.com>Dato: tor. 5. mar. 2020, 16:22Til: vippsas/vipps-magento <vipps-magento@noreply.github.com>Kopi: emilshamloo <post@supermarket.no>, Mention <mention@noreply.github.com>Emne: Re: [vippsas/vipps-magento] There is a problem with your VIPPs (#32)Hi @emilshamloo, happy to inform you that it has been fixed in new release, https://github.com/vippsas/vipps-magento/releases/tag/2.3.0

**Comment by matsjohans** [comment]
Hi, @emilshamloo 
Vipps cannot provide this kind of plugin support. We advice you to have a developer look into upgrading your module. 
Kind regards
Mats, Vipps

**Comment by voleye** [comment]
Hi @emilshamloo, yes, you have to update your Vipps module to the version 2.3.0.

Module upgrade could be not a trivial thing, it requires additional preparation to mitigate the risks, having contacts of hosting team, etc... to prevent or decrease server downtime.

You should ask your solution partner to do this or contact to [Vaimo Inc.](https://www.vaimo.com/)

I will close this issue since the root problem solved. Please, feel free to create new request in case you have any issues.

**Comment by emilshamloo** [comment]
Hello, God day.
My developer has updated the version now, but we have still the same issue.
I wonder if someone can help.
Beside, I am looking for the test telephone number which we can send test orders with.
Regards

**Comment by matsjohans** [comment]
Hi,
We have sent a new test number and additional info to your mail. You may use this for the test environment. 
Regards
Mats, Vipps

**Comment by hanaks** [comment]
Hello, I'm a developer working for emilshamloo. To clarify, there are currently two issues:

1; It's not possible to place an order with vipps payment method. The error is:
"vipps internal error. Details are available in Magento log file"

Details in the log file:
vipps main.CRITICAL: Report ID: Message: Property "DisableTmpl" does not have accessor method "getDisableTmpl" in class "Magento\Quote\Api\Data\PaymentInterface"

Magento version is 2.3.4. The error seems to be common to more payment method modules. I have temporarily fixed it by "hacking" Magento_Checkout/web/js/action/select-payment-method.js as suggested by starlyns here and on other places:
https://github.com/PayboxByVerifone/Magento-2.3.x/issues/4

Only vipps payment method is affected. Other payment methods works without this "hack".

So now it's possible to place an order with vipps. However, there is a second issue:

2; Vipps appears to be incompatible with "Swissuplabs Checkout Fields" module docs.swissuplabs.com/m2/extensions/checkout-fields
The module allows to add custom fields to checkout which then customers must fill. These fields are then accessible from Magento backend. These fields are however always blank for vipps payment method.

The Checkout Fields module creates a javascript mixin:
mixins: {
            'Magento_Checkout/js/action/place-order': {
                'Swissup_CheckoutFields/js/model/place-order-mixin': true
            },
        }
to modify placeOrder action, and adds the values to payment data. This works for other payment methods but not for vipps, which appears to not be using 'Magento_Checkout/js/action/place-order' at all.

I temporarily fixed it by injecting the code filling payment data to vendor\vipps\module-payment\view\frontend\web\js\action\set-payment-method.js

Could you please cooperate with swissuplabs to fix this incompatibility? Both modules are updated.

**Comment by emilshamloo** [comment]
Any help for solving this issue would be appreciated.

**Comment by emilshamloo** [comment]
Is there anyboady how can help us solve this issue?
It's been 8 days, my developer has wrote here!

**Comment by cloveras** [comment]
Hi

Sorry for the delay here. Vaimo, our partner who develops the Magento module, will look at this ASAP.

Christian, Vipps

**Comment by ed007m** [comment]
@hanaks, @emilshamloo 
We are working on it as we speak. We will publish fix for this issue in a new release next week and apologies for the delayed response!

**Comment by ed007m** [comment]
@hanaks 
I have a question regarding your first issue. How I can reproduce this issue?
Do you have other third-party modules installed?

**Comment by hanaks** [comment]
The error always occurs when the checkout is submitted with vipps payment method selected.

The site has these modules installed:
composer.json has these listed:
"require": {
        "composer/composer": "@alpha",
        "paalsoberg/magento-2-norwegian-language-pack": "dev-master",
        "mageplaza/magento-2-norwegian-language-pack": "dev-master",
        "swissup/firecheckout": "^1.16",
        "magento/product-community-edition": "2.3.4-p2",
        "swissup/module-delete-orders": "^1.0",
        "vipps/module-payment": "^1.3",
        "swissup/pagespeed": "^1.2",
        "swissup/pdf-invoice": "^1.0",
        "swissup/maintenance": "^2.0",
        "mageplaza/module-google-tag-manager": "^2.1",
        "swissup/recaptcha": "^1.2",
        "swissup/social-login": "^1.1",
        "swissup/argento-m2": "^1.12",
        "quickpay/magento2": "dev-QuickPay_Gateway-remake",
        "swissup/email-templates": "^1.0",
        "piwik/device-detector": "^3.12",
        "mageworx/module-ordereditormeta": "^1.6"
    },

**Comment by ed007m** [comment]
@hanaks 
What version of swissup/firecheckout you are using?

I have configured magento/ce 2.3.4-p2 (as you mentioned) and installed swissup/firecheckout:1.23.0 - which was latest one. Enabled this firecheckout inside configuration settings and added custom field to checkout page. And this works perfect for me.

Please, check screenshots below
<img width="1346" alt="img1" src="https://user-images.githubusercontent.com/6236299/83659818-b6fa7480-a5cc-11ea-9b2b-844bbf46a2d8.png">
<img width="1024" alt="img2" src="https://user-images.githubusercontent.com/6236299/83659830-bb269200-a5cc-11ea-8830-2b8dcec5b073.png">

Also I've tried to place an order using standard magento checkout, but with the same custom checkout fields. Result was the same. 

Could you, please provide more details for your  configurations? Do you have any other customizations?

**Comment by ed007m** [comment]
@hanaks 
I guess i've found a problem. You should update vipps to latest one
"vipps/module-payment": "^1.3",

Latest one is 2.3.3

**Comment by cloveras** [comment]
Hi @hanaks and @emilshamloo 

Have you updated the module, as @ed007m recommended?

Version 1.3 was released in January, and there have been several new releases since then: https://github.com/vippsas/vipps-magento/releases

Christian, Vipps

**Comment by hanaks** [comment]
I have updated
vipps/module-payment --with-dependencies
yesterday, but it didn't download anything. Version is still 1.3.11. Is the new version available for Magento 2.3.4-p2?

**Comment by ed007m** [comment]
@hanaks 
Yes, the new version also supports Magento 2.3.5-p1 and Magento 2.3.4-p2.
https://github.com/vippsas/vipps-magento/releases/tag/2.3.6
